### ISSUE TITLE
SPOE deprecated in haproxy 3.1

### ISSUE THREAD

**Issue by bzed** [corazawaf/coraza-spoa#104]
Hi,

you might want to chime into this discussion or prepare for it....

https://www.mail-archive.com/haproxy@formilux.org/msg44680.html

Bernd

**Comment by bedis** [comment]
Easier to discuss here: https://github.com/haproxy/haproxy/issues/2502

**Comment by jcchavezs** [comment]
Thanks @bzed. I had a brief chat with @bedis during Kubecon Paris and he gave me som hints on the future of SPOE. We will keep this repo for now but we should keep an eye on what is coming in https://github.com/haproxy/haproxy/issues/2502 (any clue on the deadline for 3.0 @bedis ?)

**Comment by willholley** [comment]
It looks like SPOA is [no longer being deprecated](https://github.com/haproxy/haproxy/commit/eb89a7da33ae30da3ed61570aa1597987b59dff3) in HAProxy 3.x 🎉

**Comment by jcchavezs** [comment]
yay!

**Comment by fionera** [comment]
This can be closed then ^^
