### ISSUE TITLE
Haproxy-spoa-go  is currently unmaintained.

### ISSUE THREAD

**Issue by zabojcaspamu** [corazawaf/coraza-spoa#108]
In https://github.com/criteo/haproxy-spoe-go
Please note: This repository is currently unmaintained. Please switch to project https://github.com/negasus/haproxy-spoe-go if you want to use a golang version of haproxy-spoe library.

Are there any plans to switch to this repo?

**Comment by superstes** [comment]
Looks like a duplicate issue? https://github.com/corazawaf/coraza-spoa/issues/51

**Comment by fionera** [comment]
This is fixed now :)
