### ISSUE TITLE
Refactor coraza-spoa configuration

### ISSUE THREAD

**Issue by sts** [corazawaf/coraza-spoa#30]
To make it easier to configure all settings when running coraza-spoa in a docker container, all configuration settings should be exposed as CLI parameter. 

Required Paramerters & Default configuration:
```
--bind 127.0.0.0.1:9000
--transaction-ttl 60000
--transaction_active_limit 100000
--error-log-file /dev/stdout
--server-log-file /var/log/coraza-spoa/server.log
--server-log-level debug
--debug-log-file /var/log/coraza-spoa/debug.log
--audit-log-file /var/log/coraza-spoa/audit.log
```

User required parameters should be the included seclang config:
```
--include /etc/coraza-spoa/coraza.conf
--include /etc/coraza-spoa/crs-setup.conf
--include /etc/coraza-spoa/rules/*.conf
```

Possible libraries:
- https://github.com/spf13/viper (cli & config file)
- https://github.com/spf13/cobra (cli only)

**Comment by NullIsNot0** [comment]
Taking into consideration that new agent (in experimental branch) is supporting multiple configurations called "applications", it would be easier to bind mount configuration file.

**Comment by fionera** [comment]
I like flag configuration but since we are allowing multiple applications/configurations this is not feasible/error prone. Gonna close this one
