### ISSUE TITLE
logging issue

### ISSUE THREAD

**Issue by adsorrentino** [corazawaf/coraza-spoa#31]
Hello, i've been testing coraza-spoa and found that when a rule triggers, it's written to the config.yml file.
It also writes the events to the file i configured in /var/log.
ie: my config.yml after an event

  # The transaction cache lifetime(ms)
  transaction_ttl: 60000
  # The transaction cache limit
  transaction_active_limit: 100000
coraza2022/08/03 09:36:32 spoa.go:122: [client "192.168.1.10"] Coraza: Warning. Invalid character in request (outside of very strict set) [file "/etc/coraza-spoa/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "0"] [id "920273"] [rev ""] [msg "Invalid character in request (outside of very strict set)"] [data "ARGS:something=../../etc/passwd"] [severity "critical"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS"] [tag "capec/1000/210/272"] [tag "paranoia-level/4"] [hostname ""] [uri "/?something=../../etc/passwd"] [unique_id "90c441a0-ad38-4bb3-9e01-4cac0c939ce7"]

best regards
Alejandro

**Comment by adsorrentino** [comment]
Hello, i'm updating the issue a bit. I tried to compile the agent in a different server with another linux distribution and also tried the docker container using this Dockerfile (https://github.com/jessequinn/coraza-spoa/tree/feature-Dockerfile/docker). 
The results remain the same, the agent keeps login to the config.yml file, when you restart the agent it crashes due to all the extra text.

best regards
Alejandro

**Comment by jptosso** [comment]
Fixed by #32 , thank you for your report

**Comment by adsorrentino** [comment]
Juan Pablo, I've tested the fix and it's working correctly.

best regards / saludos cordiales
Alejandro
