### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by jcchavezs** [corazawaf/coraza-spoa#42]
I think until now it has been treated as an experiment but now it is being included in a [quite used library](https://github.com/jcmoraisjr/haproxy-ingress/pull/964) and I think we should spend some time and effort making `coraza-spoa` stable to not to give the impression coraza is not usable.

Another option is to archive this if no maintainer is joining we archive this repo.

In any case I curated a very basic list of issues that should be tackled by the adjoint maintainer https://github.com/corazawaf/coraza-spoa/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22

Any thoughts @mac-chaffee @sts @jptosso @NullIsNot0, any volunteering?

----

**UPDATE:** curated a [list of issues](https://github.com/corazawaf/coraza-spoa/issues?q=is%3Aissue+is%3Aopen+label%3A%22looking+for+maintainer%22) that should be tackled by maintainers

**Comment by zc-devs** [comment]
Hello there. I'm willing to be a maintainer. @jcchavezs, may I?

**Comment by jcchavezs** [comment]
Awesome @zc-devs! I will create a label that will list the issues that should be addressed by a maintainer of this project. Give me some minutes.

**Comment by jcchavezs** [comment]
@zc-devs I just created a list of issues that should be tackled. I suggest you review them, ask questions and tackle them starting from the one that looks easier to you https://github.com/corazawaf/coraza-spoa/issues?q=is%3Aissue+is%3Aopen+label%3A%22looking+for+maintainer%22. I am up for questions, you can also ask questions in the #coraza-spoa channel in https://owasp.org/slack/invite

**Comment by jptosso** [comment]
@fionera has my blessing 
@corazawaf/core-developers

**Comment by fzipi** [comment]
The @corazawaf/core-developers team welcomes the new Coraza SPOA maintainer @fionera ! 🎉 🎉 🎉 

We can now close this long standing issue.

**Comment by jcchavezs** [comment]
Yay!
