### ISSUE TITLE
E2E test

### ISSUE THREAD

**Issue by jcchavezs** [corazawaf/coraza-spoa#44]
Integrations require e2e test to make sure basic functionality and that this won't break from the beginning. This checks must run on every PR to ensure no regressions.

One good example is https://github.com/corazawaf/coraza-proxy-wasm/tree/main/e2e which spins up an envoy with the proxy wasm plugin and runs basic checks about blocking.

**Comment by sts** [comment]
I added e2e tests similar to proxy-wasm. An example run is here: https://github.com/corazawaf/coraza-spoa/actions/runs/3795854054/jobs/6455386316
