### ISSUE TITLE
Request without a query parameter results in an error

### ISSUE THREAD

**Issue by sts** [corazawaf/coraza-spoa#5]
When sending a request without query arguments, coraza-spoa will by default [log it as an error](https://github.com/corazawaf/coraza-spoa/blob/11c9415375c76d9edfd43d711f2f9cfc890abe5d/internal/request.go#L70), when using the default configuration:

```
# coraza.cfg
spoe-message coraza-req
    args id=unique-id src-ip=src method=method path=path query=query version=req.ver headers=req.hdrs body=req.body
    event on-frontend-http-request
```

```
# error.log
{"level":"error","ts":"2022-05-22T08:42:08.165Z","caller":"logger/logger.go:75","msg":"invalid argument for http request query, string expected, got <nil>"}
```

Also the message could be enhanced, giving the user a hint where the error is happening, something like: `spoe received invalid argument in spoe-message for: query. string expected, got <nil>` would make it more clear that the error is happening between haproxy > spoe.

**Comment by jptosso** [comment]
Hey @sts, could you try the `fix-issue-5` branch? I have added validation for nil queries. Still, this is just a debug error, it won't make the transaction fail.

**Comment by sts** [comment]
@jptosso patch verified, the message "invalid argument for http request query" is not coming up anymore.

**Comment by jptosso** [comment]
Great, merged into master.
