### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by devasmith** [corazawaf/coraza-spoa#56]
Hi. We are evaluating this tool and we noticed that it's crashing from time to time. Output from the log:

```sh
2023-03-01T15:05:33.577718925Z stdout F {"level":"error","ts":1677683133.5776238,"msg":"failed to get transaction from cache","transaction_id":"41f17f8c-f0f1-4d5a-b2kl1-03de1a64e9g0","error":"Key not found.","app":"testcoraza"}
2023-03-01T15:05:33.579874622Z stderr F panic: runtime error: invalid memory address or nil pointer dereference
2023-03-01T15:05:33.579991989Z stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x673bcb]
2023-03-01T15:05:33.580015811Z stderr F
2023-03-01T15:05:33.580072224Z stderr F goroutine 602 [running]:
2023-03-01T15:05:33.58034082Z stderr F github.com/corazawaf/coraza-spoa/internal.(*SPOA).processResponse(0xc000b4f800, {{0xc00214e00a?, 0x50?}, 0xc002169bd0?})
2023-03-01T15:05:33.580441486Z stderr F         /app/internal/response.go:86 +0x1eeb
2023-03-01T15:05:33.580541527Z stderr F github.com/corazawaf/coraza-spoa/internal.(*SPOA).Start.func1(0xc0021743c0)
2023-03-01T15:05:33.580629496Z stderr F         /app/internal/spoa.go:59 +0xa9
2023-03-01T15:05:33.580989239Z stderr F github.com/criteo/haproxy-spoe-go.(*conn).handleNotify(0xc001edbae0, {0x3, 0x1, 0x15b7, 0x2, {0xc00214e009, 0x305, 0x3ff3}, {0xc00214e000, 0x3ffc, ...}}, ...)
2023-03-01T15:05:33.581078331Z stderr F         /go/pkg/mod/github.com/criteo/haproxy-spoe-go@v1.0.6/notify.go:109 +0xea
2023-03-01T15:05:33.581489496Z stderr F github.com/criteo/haproxy-spoe-go.(*conn).runWorker(0xc001edbae0, {0x3, 0x1, 0x15b7, 0x1, {0xc002064009, 0x23c, 0x3ff3}, {0xc002064000, 0x3ffc, ...}}, ...)
2023-03-01T15:05:33.581587384Z stderr F         /go/pkg/mod/github.com/criteo/haproxy-spoe-go@v1.0.6/conn.go:162 +0x231
2023-03-01T15:05:33.58166379Z stderr F created by github.com/criteo/haproxy-spoe-go.(*conn).run
2023-03-01T15:05:33.581703092Z stderr F         /go/pkg/mod/github.com/criteo/haproxy-spoe-go@v1.0.6/conn.go:136 +0xbb0
```

Service is setup with default values as per documentation / examples.

**Comment by sts** [comment]
@devasmith Can you check what are the values for `timeout connect`, `timeout queue` & `timeout server` configured to in haproxy vs transaction_ttl_seconds in coraza-spoa?

**Comment by devasmith** [comment]
> @devasmith Can you check what are the values for `timeout connect`, `timeout queue` & `timeout server` configured to in haproxy vs transaction_ttl_seconds in coraza-spoa?

Hi, sorry for the late reply.

```
timeout connect         10s
timeout server          10m
```

`timeout queue` has not been configured.

We bumped `transation_ttl_seconds` from 60000 to 6000000.

It seems as the `internal/response.go` causes this error. Managed to do a workaround but we disabled the service due to a memory leak.

```
			txInterface, err := app.cache.Get(id)
			if err != nil {
				app.logger.Error("failed to get transaction from cache", zap.String("transaction_id", id), zap.String("error", err.Error()), zap.String("app", app.name))
				return nil, fmt.Errorf("failed to get transaction from cache")
			}
```

**Comment by bananasgroup** [comment]
So please, how can we fix this problem. I have now knowledge at Go language. 
What does above code mean? And where can I paste this code to?

**Comment by NullIsNot0** [comment]
> > @devasmith Can you check what are the values for `timeout connect`, `timeout queue` & `timeout server` configured to in haproxy vs transaction_ttl_seconds in coraza-spoa?
> 
> Hi, sorry for the late reply.
> 
> ```
> timeout connect         10s
> timeout server          10m
> ```
> 
> `timeout queue` has not been configured.
> 
> We bumped `transation_ttl_seconds` from 60000 to 6000000.
> 
> It seems as the `internal/response.go` causes this error. Managed to do a workaround but we disabled the service due to a memory leak.
> 
> ```
> 			txInterface, err := app.cache.Get(id)
> 			if err != nil {
> 				app.logger.Error("failed to get transaction from cache", zap.String("transaction_id", id), zap.String("error", err.Error()), zap.String("app", app.name))
> 				return nil, fmt.Errorf("failed to get transaction from cache")
> 			}
> ```

If you use `transaction_ttl_seconds`, your coraza-spoa is old. Please update it and use `transaction_ttl_ms`. Now it's fixed and the value should be 600000 (for 10 minutes). Please be aware that every session you store, takes some memoro, so be sure to have enough memory for your server.

**Comment by devasmith** [comment]
> > > @devasmith Can you check what are the values for `timeout connect`, `timeout queue` & `timeout server` configured to in haproxy vs transaction_ttl_seconds in coraza-spoa?
> > 
> > 
> > Hi, sorry for the late reply.
> > ```
> > timeout connect         10s
> > timeout server          10m
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `timeout queue` has not been configured.
> > We bumped `transation_ttl_seconds` from 60000 to 6000000.
> > It seems as the `internal/response.go` causes this error. Managed to do a workaround but we disabled the service due to a memory leak.
> > ```
> > 			txInterface, err := app.cache.Get(id)
> > 			if err != nil {
> > 				app.logger.Error("failed to get transaction from cache", zap.String("transaction_id", id), zap.String("error", err.Error()), zap.String("app", app.name))
> > 				return nil, fmt.Errorf("failed to get transaction from cache")
> > 			}
> > ```
> 
> If you use `transaction_ttl_seconds`, your coraza-spoa is old. Please update it and use `transaction_ttl_ms`. There was an inconsistency in session ID storage length units. Now it's fixed and the value should be 600000 (for 10 minutes). Please be aware that every session you store, takes some memoro, so be sure to have enough memory for your server.

I copied the value from the documentation that might have been old, we are using `transaction_ttl_ms` and had set value to `6000000` ms rather than `600000` ms which might have been too much.

We temporarily disabled the service due to the memory leak we encountered and haven't had time to look further into it but we would like to test this out again.

**Comment by bananasgroup** [comment]
I download coreruleset v3.3.4 rules, then I start coraza-spoa, then I got this error:
$ Loading 1 applications
{"level":"error","ts":1680775797.2646449,"msg":"unable to create waf instance","app":"haproxy","error":"invalid WAF config: failed to compile rule (error parsing regexp: invalid or unsupported Perl syntax: `(?<`): FILES_NAMES|FILES \"@rx (?<!&(?:[aAoOuUyY]uml)|&(?:[aAeEiIoOuU]circ)|&(?:[eEiIoOuUyY]acute)|&(?:[aAeEiIoOuU]grave)|&(?:[cC]cedil)|&(?:[aAnNoO]tilde)|&(?:amp)|&(?:apos));|['\\\"=]\" \"id:920120,phase:2,block,t:none,t:urlDecodeUni,msg:'Attempted multipart/form-data bypass',logdata:'%{MATCHED_VAR}',tag:'application-multi',tag:'language-multi',tag:'platform-multi',tag:'attack-protocol',tag:'paranoia-level/1',tag:'OWASP_CRS',tag:'capec/1000/210/272',ver:'OWASP_CRS/3.3.4',severity:'CRITICAL',setvar:'tx.anomaly_score_pl1=+%{tx.critical_anomaly_score}'\""}
panic: invalid WAF config: failed to compile rule (error parsing regexp: invalid or unsupported Perl syntax: `(?<`): FILES_NAMES|FILES "@rx (?<!&(?:[aAoOuUyY]uml)|&(?:[aAeEiIoOuU]circ)|&(?:[eEiIoOuUyY]acute)|&(?:[aAeEiIoOuU]grave)|&(?:[cC]cedil)|&(?:[aAnNoO]tilde)|&(?:amp)|&(?:apos));|['\"=]" "id:920120,phase:2,block,t:none,t:urlDecodeUni,msg:'Attempted multipart/form-data bypass',logdata:'%{MATCHED_VAR}',tag:'application-multi',tag:'language-multi',tag:'platform-multi',tag:'attack-protocol',tag:'paranoia-level/1',tag:'OWASP_CRS',tag:'capec/1000/210/272',ver:'OWASP_CRS/3.3.4',severity:'CRITICAL',setvar:'tx.anomaly_score_pl1=+%{tx.critical_anomaly_score}'"

**Comment by bananasgroup** [comment]
I configured audit log like this:
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:(5|4)(0|1)[0-9])$"
SecAuditLogParts ABIJDEFHZ
SecAuditLogType Serial
SecAuditLog /var/log/corazaaudit.log

But it does not write any log to that file (/var/log/corazaaudit.log), it just show all audit log on screen. How can I write audit log to the file?

**Comment by bananasgroup** [comment]
coraza-spoa sometime show this warning:
INFO[0000] spoe session ending with: write frame: write tcp 127.0.0.1:9000->127.0.0.1:16858: write: broken pipe 
WARN[0000] spoe: error handling connection: write frame: write tcp 127.0.0.1:9000->127.0.0.1:16858: write: broken pipe 
INFO[0000] spoe session ending with: write frame: write tcp 127.0.0.1:9000->127.0.0.1:16860: write: broken pipe 
WARN[0000] spoe: error handling connection: write frame: write tcp 127.0.0.1:9000->127.0.0.1:16860: write: broken pipe 
INFO[0000] spoe session ending with: write frame: write tcp 127.0.0.1:9000->127.0.0.1:16864: write: broken pipe 
WARN[0000] spoe: error handling connection: write frame: write tcp 127.0.0.1:9000->127.0.0.1:16864: write: broken pipe 
INFO[0000] spoe session ending with: write frame: write tcp 127.0.0.1:9000->127.0.0.1:16866: write: broken pipe 
WARN[0000] spoe: error handling connection: write frame: write tcp 127.0.0.1:9000->127.0.0.1:16866: write: broken pipe 
INFO[0000] spoe session ending with: write frame: write tcp 127.0.0.1:9000->127.0.0.1:16878: write: broken pipe 
WARN[0000] spoe: error handling connection: write frame: write tcp 127.0.0.1:9000->127.0.0.1:16878: write: broken pipe 
INFO[0000] spoe session ending with: write frame: write tcp 127.0.0.1:9000->127.0.0.1:16880: write: broken pipe 
WARN[0000] spoe: error handling connection: write frame: write tcp 127.0.0.1:9000->127.0.0.1:16880: write: broken pipe 
INFO[0000] spoe session ending with: write frame: write tcp 127.0.0.1:9000->127.0.0.1:16886: write: broken pipe 
WARN[0000] spoe: error handling connection: write frame: write tcp 127.0.0.1:9000->127.0.0.1:16886: write: broken pipe 
INFO[0000] spoe session ending with: write frame: write tcp 127.0.0.1:9000->127.0.0.1:16892: write: broken pipe 
WARN[0000] spoe: error handling connection: write frame: write tcp 127.0.0.1:9000->127.0.0.1:16892: write: broken pipe 
INFO[0000] spoe session ending with: write frame: write tcp 127.0.0.1:9000->127.0.0.1:16896: write: broken pipe 
WARN[0000] spoe: error handling connection: write frame: write tcp 127.0.0.1:9000->127.0.0.1:16896: write: broken pipe 
INFO[0001] spoe session ending with: write frame: write tcp 127.0.0.1:9000->127.0.0.1:16898: write: broken pipe 
WARN[0001] spoe: error handling connection: write frame: write tcp 127.0.0.1:9000->127.0.0.1:16898: write: broken pipe 

How can I fix this?

**Comment by bananasgroup** [comment]
coraza service took too high memory, over 80%. how can I reduce this?

**Comment by bananasgroup** [comment]
After running coraza-spoa, backend log shows proxy ip instead of public source IP. Can I change this? I prefer showing original public ip in backend log.

**Comment by bananasgroup** [comment]
that does not solve my problem. my coraza.cfg is:
# https://github.com/haproxy/haproxy/blob/master/doc/SPOE.txt
[coraza]
spoe-agent coraza-agent
    messages coraza-req coraza-res
    option var-prefix coraza
    option set-on-error error
    timeout hello      100ms
    timeout idle       2m
    timeout processing 500ms
    use-backend coraza-spoa
    log global

spoe-message coraza-req
    args app=str(haproxy) id=unique-id src-ip=src src-port=src_port dst-ip=dst dst-port=dst_port method=method path=path query=query version=req.ver headers=req.hdrs body=req.body
    event on-frontend-http-request

spoe-message coraza-res
    args app=str(haproxy) id=unique-id version=res.ver status=status
    event on-http-response

Backend log still display proxy LAN IP instead of sourc public IP.

PS: Haproxy show parsing [/etc/haproxy/coraza.cfg:18] : 'args': unknown fetch method 'res.hdrs' so I removed headers=res.hdrs and body=res.body.

**Comment by jptosso** [comment]
Performance issues are probably related to Coraza version, I will create a PR to upgrade it. Other problem you might face, by design, is the transaction ttl cache. A good solution would be to add an option to completely disable response processing, therefor disabling transaction ttl cache.

**Comment by jptosso** [comment]
Can you try with this? https://github.com/corazawaf/coraza-spoa/pull/60 it seems to address many of the existing problems

**Comment by GilchristT** [comment]
I'm seeing the same issue after changing my HAProxy timeouts. I've changed the HAProxy settings back to what I thought are the defaults but still seeing the same issue.

Could someone clarify exactly which settings in HAProxy should correlate with which settings in the SPOA config?

I'm running in Docker and using an image built in the last week.

**Comment by devasmith** [comment]
I've run the latest release since a week and I've not seen any more crashes. Maybe we can close this one?

**Comment by jcchavezs** [comment]
Awesome.
