### ISSUE TITLE
Adds readme/command to run a example application

### ISSUE THREAD

**Issue by jcchavezs** [corazawaf/coraza-spoa#65]
It should be trivial to run an example with a single command. It helps to triage issues and reproduce users issues.

For example https://owasp.slack.com/archives/C03H4LQSHNZ/p1686216435947609

**Comment by zc-devs** [comment]
What I use is already [in documentation](https://github.com/corazawaf/coraza-spoa#docker).

**Comment by fionera** [comment]
We have a working docker setup. With the complexity/amount of moving parts this will probably the only example to get it up quickly
