### ISSUE TITLE
Error  sample_app, error: Key not found

### ISSUE THREAD

**Issue by sstsarel** [corazawaf/coraza-spoa#93]
level=error msg="spoe error during first notify handle: handle notify: failed to get transaction from cache, transaction_id: , app: sample_app, error: Key not found."

I picked up the container as written here
Build the coraza-spoa image docker-compose build
Run haproxy, coraza-spoa and a mock server docker-compose up

when will I make a request for 4000
I receive an error message ( level=error msg="spoe error during first notify handle: handle notify: failed to get transaction from cache, transaction_id: 5dae59a1-687a-4ed1-b3d1-240e5a74d4b2, app: sample_app, error: Key not found.") 
If you comment out the #spoe-message coraza-res block then everything works fine

ubuntu 22.04 
Docker version 24.0.6

**Comment by sylweltan** [comment]
The same error here. When set
`no_response_check: false`
in config.yaml it started working

**Comment by gorzelvk** [comment]
anyone found a fix for it? commenting out #spoe-message coraza-res makes coraza not work properly, setting no_response_check to false doesnt change a thing

**Comment by fionera** [comment]
It seems like either the cache is too small or time timeout too low. Since this is an issue created for the previous implementation, I am closing this for now
