### ISSUE TITLE
Listen "server" on .sock

### ISSUE THREAD

**Issue by UnveilTech** [corazawaf/coraza-spoa#96]
Hello,
the doc indicates the server "s1" on ip:port as below:
_# /etc/haproxy/haproxy.cfg
....
backend coraza-spoa
    mode tcp
    server s1 **127.0.0.1:9000**_

do you think it could makes sense to also use a .sock (**/var/run/coaza-spoa.sock**), it could be nice to have that instead of having dozens of open ports on the computer and it might be faster in transaction..

thanks,
bye Fred

**Comment by fionera** [comment]
This is supported now and yes it is a lot faster as you skip the tcp stack

**Comment by UnveilTech** [comment]
fionera,

great news !!!

thanks a lot,
bye Fred

**Comment by fionera** [comment]
@xkpx64 You have to prepend the scheme `unix:///var/run/coraza-spoa.sock`
